name: 'Terraform'

on:
  push:
  pull_request:

env:
  TF_VAR_discord_token: "${{ secrets.DISCORD_API_TOKEN }}"

permissions:
  contents: read

jobs:
  test:
    name: 'Test'

    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code.
        uses: actions/checkout@v4

      - name: Setup Terraform.
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init.
        working-directory: "./tf"
        run: terraform init

      - name: Terraform Format.
        working-directory: "./tf"
        run: terraform fmt -check --diff --recursive

  build:
    name: 'Build'
    needs: test

    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code.
        uses: actions/checkout@v4

      - name: Setup Terraform.
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init.
        working-directory: "./tf"
        run: terraform init

      - name: Terraform Plan.
        working-directory: "./tf"
        run: terraform plan -input=false

      - name: Archive plan.
        uses: actions/upload-artifact@v4
        with:
          name: plan.out
          path: ./tf/plan.out
          retention-days: 7


  deploy:
    name: 'Deploy'
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code.
        uses: actions/checkout@v4

      - name: Setup Terraform.
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init.
        working-directory: "./tf"
        run: terraform init

      - name: Terraform Apply.
        working-directory: "./tf"
        run: terraform apply -auto-approve -input=false -lock=true
